name = "twa-cf-tpl"
main = "backend/src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true
head_sampling_rate = 0.1

# KV Namespaces (will be updated during deployment with real IDs)
# [[kv_namespaces]]
# binding = "SESSIONS"
# id = "sessions"
# preview_id = "sessions"


[env.local]
name = "twa-cf-tpl-local"

[env.preview]
name = "twa-cf-tpl-preview"

[env.production]
name = "twa-cf-tpl-prod"

# Non-secret environment variables
[vars]
ENVIRONMENT = "local"
BOT_TOKEN = "$TELEGRAM_BOT_TOKEN"

# Secret environment variables (set via wrangler secret put)
# BOT_TOKEN - Telegram bot token for initData validation

[env.preview.vars]
ENVIRONMENT = "preview"

[env.production.vars]
ENVIRONMENT = "production"