name = "twa-cf-tpl"
main = "backend/src/index.ts"
compatibility_date = "2024-09-01"

[env.local]
name = "twa-cf-tpl-local"

[env.preview]
name = "twa-cf-tpl-preview"

[env.production]
name = "twa-cf-tpl-prod"

# Non-secret environment variables
[vars]
ENVIRONMENT = "local"

[env.preview.vars]
ENVIRONMENT = "preview"

[env.production.vars]
ENVIRONMENT = "production"