name = "fleamarket-twa"
main = "backend/src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
account_id = "e023ec3576222c6a7b6cdf933de3d915"

[observability.logs]
enabled = true
head_sampling_rate = 0.1

# KV Namespaces - create a namespace in Cloudflare dashboard and replace with actual ID
[[kv_namespaces]]
binding = "SESSIONS"
id = "somekv-id"



# D1 Databases
[[d1_databases]]
binding = "DB"
database_name = "fleamarket-db"
database_id = "somedatabaseid"
migrations_dir = "backend/drizzle/migrations"


# R2 Buckets
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "fleamarket-images"


# Non-secret environment variables
[vars]
ENVIRONMENT = "production"
PAGES_URL = "https://fleamarket-twa.pages.dev"

# Pages configuration
pages_build_output_dir = "frontend/dist"
