name = "twa-cf-tpl"
main = "backend/src/index.ts"
compatibility_date = "2024-09-01"

[env.local]
name = "twa-cf-tpl-local"

[env.preview]
name = "twa-cf-tpl-preview"

[env.production]
name = "twa-cf-tpl-prod"

# Variables that are the same across all environments
[vars]
ENVIRONMENT = "local"
TELEGRAM_BOT_TOKEN = "7747466363:AAFJ6APrEtFeGDT36epoD8ZAb7TaIl3BwNQ"
TELEGRAM_ADMIN_ID = "62408647"

# Environment-specific variables
[env.preview.vars]
ENVIRONMENT = "preview"

[env.production.vars]
ENVIRONMENT = "prod"