name = "telegram-webapp-cloudflare-template"
main = "backend/src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
account_id = "e023ec3576222c6a7b6cdf933de3d915"

[observability.logs]
enabled = true
head_sampling_rate = 0.1

# KV Namespaces - create a namespace in Cloudflare dashboard and replace with actual ID
[[kv_namespaces]]
binding = "SESSIONS"
id = "c60b9a7fb0714e16bcf5200334ea23a1"



# D1 Databases
[[d1_databases]]
binding = "DB"
database_name = "telefare_prod_db"
database_id = "a5c2804a-090a-4597-ba53-e571d36e3010"
migrations_dir = "backend/drizzle/migrations"


# R2 Buckets
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "telefare-images"


# Non-secret environment variables
[vars]
ENVIRONMENT = "production"
PAGES_URL = "https://telefare-pages.pages.dev"

# Pages configuration
pages_build_output_dir = "frontend/dist"
