name = "twa-cf-tpl"
main = "backend/src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true
head_sampling_rate = 0.1

# KV Namespaces - create a namespace in Cloudflare dashboard and replace with actual ID
[[kv_namespaces]]
binding = "SESSIONS"
id = "214af53e9fd44c18ba913499a606dd70"

# Non-secret environment variables
[vars]
ENVIRONMENT = "production"

# Secret environment variables (set via wrangler secret put)
# TELEGRAM_BOT_TOKEN - Telegram bot token for initData validation
# TELEGRAM_ADMIN_ID - Admin user ID