name = "twa-cf-tpl"
main = "backend/src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
account_id = "e023ec3576222c6a7b6cdf933de3d915"

[observability.logs]
enabled = true
head_sampling_rate = 0.1

# KV Namespaces - create a namespace in Cloudflare dashboard and replace with actual ID
[[kv_namespaces]]
binding = "SESSIONS"
id = "214af53e9fd44c18ba913499a606dd70"

# D1 Databases
[[d1_databases]]
binding = "DB"
database_name = "twa-tpl-db"
database_id = "c9fe2099-a700-4a59-8294-08e8e1049ca7"
migrations_dir = "backend/drizzle/migrations"



# Non-secret environment variables
[vars]
ENVIRONMENT = "production"
