openapi: 3.0.3
info:
  title: Telegram Web App API
  description: API endpoints for the Telegram Web App frontend
  version: 1.0.0

servers:
  - url: https://app.example.com/api
    description: Production server
  - url: https://preview.app.example.com/api
    description: Preview server

paths:
  /hello:
    get:
      summary: Get hello world message
      description: Returns a simple hello world message for the web app (no authentication required for template)
      responses:
        '200':
          description: Hello message retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    HelloResponse:
      type: object
      properties:
        message:
          type: string
          example: "Hello World"
        timestamp:
          type: string
          format: date-time
        environment:
          type: string
          enum: [local, preview, prod]
      required:
        - message
        - timestamp
        - environment

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
      required:
        - error
        - message
        - timestamp