name: Build & Test

on:
  workflow_call:

env:
  NODE_VERSION: '20'

jobs:
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Lint backend
        run: |
          cd backend
          npm run lint

      - name: Type check backend
        run: |
          cd backend
          npm run typecheck

      - name: Run backend tests
        run: |
          cd backend
          npm test -- --run

  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Lint frontend
        run: |
          cd frontend
          npm run lint

      - name: Type check frontend
        run: |
          cd frontend
          npm run typecheck

      - name: Run frontend tests
        run: |
          cd frontend
          npm test -- --run

      - name: Build frontend
        run: |
          cd frontend
          npm run build