name: Deploy Cloudflare Worker

on:
  workflow_call:

env:
  NODE_VERSION: '18'

jobs:
  deploy-worker:
    name: Deploy Worker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Set Cloudflare Secrets
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: secret put TELEGRAM_BOT_TOKEN
          workingDirectory: ./backend
        env:
          WRANGLER_INPUT: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Deploy to Cloudflare Workers
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          workingDirectory: ./backend

      - name: Get Worker URL
        id: worker-url
        run: |
          # Get deployment URL from wrangler output
          WORKER_URL=$(echo "${{ steps.deploy.outputs.deployment-url }}" | tr -d '\n')
          echo "url=$WORKER_URL" >> $GITHUB_OUTPUT

      - name: Test Worker Health
        run: |
          sleep 10
          echo "Testing Worker at: ${{ steps.worker-url.outputs.url }}"

          # Test health endpoint
          response=$(curl -s -o /dev/null -w "%{http_code}" "${{ steps.worker-url.outputs.url }}/health")
          if [ "$response" != "200" ]; then
            echo "❌ Health check failed with status $response"
            exit 1
          fi

          # Test hello endpoint
          response=$(curl -s -o /dev/null -w "%{http_code}" "${{ steps.worker-url.outputs.url }}/api/hello")
          if [ "$response" != "200" ]; then
            echo "❌ Hello API check failed with status $response"
            exit 1
          fi

          echo "Worker deployment verified"

