name: Deploy Cloudflare Pages

on:
  workflow_call:

env:
  NODE_VERSION: '20'

jobs:
  deploy-pages:
    name: Deploy Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Deploy to Cloudflare Pages
        id: deploy-pages
        run: |
          cd frontend
          npx wrangler pages deploy dist --project-name=twa-cf-tpl
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Get Pages URL
        id: pages-url
        run: |
          # Use default pages URL format for now
          PAGES_URL="https://twa-cf-tpl.pages.dev"
          echo "url=$PAGES_URL" >> $GITHUB_OUTPUT

      - name: Test Pages Deployment
        run: |
          sleep 15
          echo "Testing Pages at: ${{ steps.pages-url.outputs.url }}"

          # Test if pages serve the index.html
          response=$(curl -s -o /dev/null -w "%{http_code}" "${{ steps.pages-url.outputs.url }}/")
          if [ "$response" != "200" ]; then
            echo "⚠️  Pages check returned status $response (may be normal for preview URLs)"
          else
            echo "Pages deployment verified"
          fi

