name: Deploy Pipeline

on:
  push:
    branches: ['main']
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  build-and-test:
    name: "Build & Test"
    uses: ./.github/workflows/1-build-test.yml
    secrets: inherit

  deploy-worker:
    name: "Deploy Worker"
    needs: build-and-test
    uses: ./.github/workflows/2-deploy-worker.yml
    secrets: inherit

  deploy-pages:
    name: "Deploy Pages"
    needs: [build-and-test, deploy-worker]
    uses: ./.github/workflows/3-deploy-pages.yml
    secrets: inherit

  setup-webhook:
    name: "Setup Webhook"
    needs: [build-and-test, deploy-worker, deploy-pages]
    uses: ./.github/workflows/4-setup-webhook.yml
    secrets: inherit

  pipeline-summary:
    name: "Pipeline Summary"
    runs-on: ubuntu-latest
    needs: [build-and-test, deploy-worker, deploy-pages, setup-webhook]
    if: always()
    steps:
      - name: Pipeline Status
        run: |
          echo "Trigger: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Pipeline Status: SUCCESS"